name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ESTE PASO ES EL QUE ARREGLA TU ERROR
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Forzamos la versión que Astro pide

      - name: Install, build, and upload with Astro
        uses: withastro/action@v3